### ISSUE TITLE
Parameters and placeholder for the startup script

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#25]
### What Should Be Added
If I start the server with start <Server>, this server does use the port in its server.properties normaly. You could add some of this [Spigots Parameters](https://www.spigotmc.org/wiki/start-up-parameters/) in default. You can autoset for example the servers port (-p %serverport%).

In the BungeeCords SubServers config.yml is a option to set a port. With the named [Spigot Parameters](https://www.spigotmc.org/wiki/start-up-parameters/) and your configoption a placeholder %port% the Executable could be set easier for users. My example:

```
YAML
Servers:
  'server1':  #<- equals %name%
    Enabled: true
    Display: 'Lobby'  #<- equals %displayname%
    Host: 'Default'
    Group:
    - '%displayname%'
    Port: 20000  #<- equals %port%
    Motd: ''
    Log: false
    Directory: './%name%'
    Executable: 'java -Dcom.mojang.eula.agree=true -Djline.terminal=jline.UnsupportedTerminal -jar -Dfile.encoding=UTF8 -server paperclip.jar -h 127.0.0.1 -p %port%'
    Stop-Command: 'stop'
    Stop-Action: 'NONE'
    Run-On-Launch: true
    Restricted: false
    Incompatible:
    - 'NONE'
    Hidden: false
```
minram and maxram could be useless

### Why It Should be Added
It would make servermanaging a bit easier (So I don't have to edit the same numbers several time).

### What's The Alternative
Don't know.
