### ISSUE TITLE
How to use variables in other files?

### ISSUE THREAD

**Issue by samuelh2005** [ME1312/SubServers-2#78]
Currently I want to replace a plugin's config variable that is loaded from a master template, like this.
```
\Templates
├───A
│       template.yml
│
├───B
│       template.yml
│
└───Master
    │   template.yml
    │
    └───plugins
        └───LuckPerms
                config.yml
```

In A and B's template I have
```yaml
Template:
...
  Build:
...
    Import:
    - Master
    Replace:
    - '/plugins/LuckPerms/config.yml' # This comes from the 'Master' template
    Replacements:
      'luckperms_server': 'bedwars' # the value will be different on both A and B
```

In the LuckPerm's config.yml I have tried
```yaml
server: $luckperms_server$
server: luckperms_server
```
Also I have tried to change the A and B's replacements to
```yaml
    Replacements:
      'server': 'bedwars'
```
but it still seems like the server value is not being  updated when I run
```/sub update aServer A```
and yes, the A template
```yaml
Template:
  Enabled: true
...
  Build:
...
    Can-Update: true
    Update-Files: true
    Update-Settings: true
```
Also I tried to delete the generated SubServer's LuckPerm config but the same problem persists.
